### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_ec2#1]
Hey @kyleaa, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are a major contributor to the EC2 service in ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by kyleaa** [comment]
Yes, I am interested.

**Comment by kyleaa** [comment]
@benwilson512 I think this one got lost - I'm interested in supporting this service.

**Comment by benwilson512** [comment]
Hey! Apologies, let's get things hooked up.

**Comment by benwilson512** [comment]
Do note that @occurr and @bearleethere are also added as maintainers, as they made a large number of contributions as well and have been involved in some of the other services.
