### ISSUE TITLE
Well Formed Structs

### ISSUE THREAD

**Issue by veverkap** [ex-aws/ex_aws_ec2#4]
This is more of a contribution question.

Is there any interest in adding well-formed structs for the responses?  As it is now, you need to parse the XML returned from the request.  Would there be any interest in having that XML parsed and formatted?

**Comment by fmcgeough** [comment]
It'd be beneficial to collect the definitions for how to parse for sure. The only thing that I'm using at the moment is describe_instances. I use this to parse the response body with SweetXml. 

```
      ~x"//reservationSet/item/instancesSet/item"l,
      instance_id: ~x"./instanceId/text()"s,
      dns_name: ~x"./dnsName/text()"s,
      ip_address: ~x"./ipAddress/text()"s,
      private_ip_address: ~x"./privateIpAddress/text()"s,
      launch_time: ~x"./launchTime/text()"s,
      instance_type: ~x"./instanceType/text()"s,
      key_name: ~x"./keyName/text()"s,
      instance_state: ~x"./instanceState/name/text()"s,
      availability_zone: ~x"./placement/availabilityZone/text()"s,
      monitoring: ~x"./monitoring/state/text()"s,
      vpc_id: ~x"./networkInterfaceSet/item/vpcId/text()"s,
      group_set: [
        ~x".//networkInterfaceSet/item/groupSet/item"l,
        group_name: ~x"./groupName/text()"s,
        group_id: ~x"./groupId/text()"s
      ],
      tag_set: [
        ~x".//tagSet/item"l,
        key: ~x"./key/text()"s,
        value: ~x"./value/text()"s
      ]
```

you can see I'm skipping over some elements so the result isn't an 1-to-1 map. A reference implementation would need everything I'd think.

**Comment by lawik** [comment]
Oh, I've spent hours trying to figure out why I'm not getting a "proper" response. Considering I have the sweetxml lib included in dependencies I really thought I would get some kind of struct. Good to know that this is to be expected.
